version: "3.7"

services:
  db:
    image: postgres:15-alpine3.18
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-coffeezone_db}
      - POSTGRES_USER=${POSTGRES_USER:-coffeezone_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-coffeezone_user}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - ${PGDATA_DIR:-pgdata}:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
    driver: local
