version: "3.7"

services:
  db:
    image: postgres:15-alpine3.18
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-coffeezone_db}
      - POSTGRES_USER=${POSTGRES_USER:-coffeezone_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-coffeezone_user}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - ${PGDATA_DIR:-pgdata}:/var/lib/postgresql/data
    restart: always
    networks:
      - bridge
  scraper:
    &scraper
    image: coffeezone:latest
    build: .
    depends_on:
      - db
    environment:
     - PG_CONN=postgresql://${POSTGRES_USER:-coffeezone_user}:${POSTGRES_PASSWORD:-coffeezone_user}@db/${POSTGRES_DB:-coffeezone_db}?sslmode=disable
    command: >
      sh -c "migrate -path ./migrations -database $$PG_CONN up &&
             scraper --database $$PG_CONN vladimir.zoon.ru"
    restart: always
    networks:
      - bridge
  rest:
    <<: *scraper
    command: >
      sh -c "rest --database $$PG_CONN"
    ports:
      - "${GIN_PORT:-8080}:8080"

volumes:
  pgdata:
    driver: local

networks:
  bridge:
    driver: bridge
